import { defineType, defineField } from "sanity";

export default defineType({
  name: "formField",
  type: "document",
  title: "Form Field",
  fields: [
    defineField({ name: "label", type: "string", title: "Field Label" }),
    defineField({
      name: "fieldType",
      type: "string",
      title: "Field Type",
      options: {
        list: [
          { title: "Text", value: "text" },
          { title: "Number", value: "number" },
          { title: "Email", value: "email" },
          { title: "Telephone", value: "tel" },
          { title: "Password", value: "password" },
          { title: "Textarea", value: "textarea" },
          { title: "Dropdown", value: "dropdown" },
          { title: "Checkbox", value: "checkbox" },
          { title: "Checkbox Group", value: "checkboxGroup" },
          { title: "Radio", value: "radio" },
          // { title: "File", value: "file" },
        ],
      },
    }),
    defineField({ 
      name: "placeholder",
      type: "string",
      title: "Placeholder",
      hidden: ({ parent }) => parent?.fieldType === "checkbox" || parent?.fieldType === "radio" || parent?.fieldType === "checkboxGroup",
     }),
    // defineField({
    //   name: "multiple",
    //   type: "boolean",
    //   title: "Multiple Files",
    //   initialValue: false, 
    //   hidden: ({ parent }) =>
    //     !["file"].includes(parent?.fieldType),
    // }),
    defineField({ name: "required", type: "boolean", title: "Required", initialValue: false }),
    defineField({ name: "disabled", type: "boolean", title: "Disabled", initialValue: false }),
    defineField({
      name: "options",
      type: "array",
      title: "Options (for dropdown or radio checkbox group)",
      of: [{ type: "string" }],
      hidden: ({ parent }) =>
        !["dropdown", "radio", "checkboxGroup"].includes(parent?.fieldType),
    }),
    defineField({
      name: "fieldWidth",
      type: "string",
      title: "Field Width",
      description: "Choose the width of the field. That width will be applied to the desktop view only.",
      options: {
        list: [
          { title: "Full Width", value: "full" },
          { title: "Half Width", value: "half" },
        ],
      },
      initialValue: "full",
      validation: (Rule) => Rule.required().error("Field width is required"),
    }),
    defineField({
      name: "allowedCountries",
      type: "array",
      title: "Allowed Countries",
      description: "Select the countries to show in the phone input dropdown. Leave empty to show all countries.",
      of: [
        {
          type: "string",
          options: {
            list: [
              { title: "🇦🇫 Afghanistan (+93)", value: "AF" },
              { title: "🇦🇱 Albania (+355)", value: "AL" },
              { title: "🇩🇿 Algeria (+213)", value: "DZ" },
              { title: "🇦🇩 Andorra (+376)", value: "AD" },
              { title: "🇦🇴 Angola (+244)", value: "AO" },
              { title: "🇦🇷 Argentina (+54)", value: "AR" },
              { title: "🇦🇲 Armenia (+374)", value: "AM" },
              { title: "🇦🇺 Australia (+61)", value: "AU" },
              { title: "🇦🇹 Austria (+43)", value: "AT" },
              { title: "🇦🇿 Azerbaijan (+994)", value: "AZ" },
              { title: "🇧🇸 Bahamas (+1-242)", value: "BS" },
              { title: "🇧🇭 Bahrain (+973)", value: "BH" },
              { title: "🇧🇩 Bangladesh (+880)", value: "BD" },
              { title: "🇧🇧 Barbados (+1-246)", value: "BB" },
              { title: "🇧🇾 Belarus (+375)", value: "BY" },
              { title: "🇧🇪 Belgium (+32)", value: "BE" },
              { title: "🇧🇿 Belize (+501)", value: "BZ" },
              { title: "🇧🇯 Benin (+229)", value: "BJ" },
              { title: "🇧🇹 Bhutan (+975)", value: "BT" },
              { title: "🇧🇴 Bolivia (+591)", value: "BO" },
              { title: "🇧🇦 Bosnia and Herzegovina (+387)", value: "BA" },
              { title: "🇧🇼 Botswana (+267)", value: "BW" },
              { title: "🇧🇷 Brazil (+55)", value: "BR" },
              { title: "🇧🇳 Brunei (+673)", value: "BN" },
              { title: "🇧🇬 Bulgaria (+359)", value: "BG" },
              { title: "🇧🇫 Burkina Faso (+226)", value: "BF" },
              { title: "🇧🇮 Burundi (+257)", value: "BI" },
              { title: "🇰🇭 Cambodia (+855)", value: "KH" },
              { title: "🇨🇲 Cameroon (+237)", value: "CM" },
              { title: "🇨🇦 Canada (+1)", value: "CA" },
              { title: "🇨🇻 Cape Verde (+238)", value: "CV" },
              { title: "🇨🇫 Central African Republic (+236)", value: "CF" },
              { title: "🇹🇩 Chad (+235)", value: "TD" },
              { title: "🇨🇱 Chile (+56)", value: "CL" },
              { title: "🇨🇳 China (+86)", value: "CN" },
              { title: "🇨🇴 Colombia (+57)", value: "CO" },
              { title: "🇰🇲 Comoros (+269)", value: "KM" },
              { title: "🇨🇬 Congo (+242)", value: "CG" },
              { title: "🇨🇷 Costa Rica (+506)", value: "CR" },
              { title: "🇭🇷 Croatia (+385)", value: "HR" },
              { title: "🇨🇺 Cuba (+53)", value: "CU" },
              { title: "🇨🇾 Cyprus (+357)", value: "CY" },
              { title: "🇨🇿 Czech Republic (+420)", value: "CZ" },
              { title: "🇩🇰 Denmark (+45)", value: "DK" },
              { title: "🇩🇯 Djibouti (+253)", value: "DJ" },
              { title: "🇩🇲 Dominica (+1-767)", value: "DM" },
              { title: "🇩🇴 Dominican Republic (+1-809)", value: "DO" },
              { title: "🇪🇨 Ecuador (+593)", value: "EC" },
              { title: "🇪🇬 Egypt (+20)", value: "EG" },
              { title: "🇸🇻 El Salvador (+503)", value: "SV" },
              { title: "🇬🇶 Equatorial Guinea (+240)", value: "GQ" },
              { title: "🇪🇷 Eritrea (+291)", value: "ER" },
              { title: "🇪🇪 Estonia (+372)", value: "EE" },
              { title: "🇪🇹 Ethiopia (+251)", value: "ET" },
              { title: "🇫🇯 Fiji (+679)", value: "FJ" },
              { title: "🇫🇮 Finland (+358)", value: "FI" },
              { title: "🇫🇷 France (+33)", value: "FR" },
              { title: "🇬🇦 Gabon (+241)", value: "GA" },
              { title: "🇬🇲 Gambia (+220)", value: "GM" },
              { title: "🇬🇪 Georgia (+995)", value: "GE" },
              { title: "🇩🇪 Germany (+49)", value: "DE" },
              { title: "🇬🇭 Ghana (+233)", value: "GH" },
              { title: "🇬🇷 Greece (+30)", value: "GR" },
              { title: "🇬🇩 Grenada (+1-473)", value: "GD" },
              { title: "🇬🇹 Guatemala (+502)", value: "GT" },
              { title: "🇬🇳 Guinea (+224)", value: "GN" },
              { title: "🇬🇼 Guinea-Bissau (+245)", value: "GW" },
              { title: "🇬🇾 Guyana (+592)", value: "GY" },
              { title: "🇭🇹 Haiti (+509)", value: "HT" },
              { title: "🇭🇳 Honduras (+504)", value: "HN" },
              { title: "🇭🇰 Hong Kong (+852)", value: "HK" },
              { title: "🇭🇺 Hungary (+36)", value: "HU" },
              { title: "🇮🇸 Iceland (+354)", value: "IS" },
              { title: "🇮🇳 India (+91)", value: "IN" },
              { title: "🇮🇩 Indonesia (+62)", value: "ID" },
              { title: "🇮🇷 Iran (+98)", value: "IR" },
              { title: "🇮🇶 Iraq (+964)", value: "IQ" },
              { title: "🇮🇪 Ireland (+353)", value: "IE" },
              { title: "🇮🇱 Israel (+972)", value: "IL" },
              { title: "🇮🇹 Italy (+39)", value: "IT" },
              { title: "🇯🇲 Jamaica (+1-876)", value: "JM" },
              { title: "🇯🇵 Japan (+81)", value: "JP" },
              { title: "🇯🇴 Jordan (+962)", value: "JO" },
              { title: "🇰🇿 Kazakhstan (+7)", value: "KZ" },
              { title: "🇰🇪 Kenya (+254)", value: "KE" },
              { title: "🇰🇮 Kiribati (+686)", value: "KI" },
              { title: "🇰🇼 Kuwait (+965)", value: "KW" },
              { title: "🇰🇬 Kyrgyzstan (+996)", value: "KG" },
              { title: "🇱🇦 Laos (+856)", value: "LA" },
              { title: "🇱🇻 Latvia (+371)", value: "LV" },
              { title: "🇱🇧 Lebanon (+961)", value: "LB" },
              { title: "🇱🇸 Lesotho (+266)", value: "LS" },
              { title: "🇱🇷 Liberia (+231)", value: "LR" },
              { title: "🇱🇾 Libya (+218)", value: "LY" },
              { title: "🇱🇮 Liechtenstein (+423)", value: "LI" },
              { title: "🇱🇹 Lithuania (+370)", value: "LT" },
              { title: "🇱🇺 Luxembourg (+352)", value: "LU" },
              { title: "🇲🇴 Macau (+853)", value: "MO" },
              { title: "🇲🇬 Madagascar (+261)", value: "MG" },
              { title: "🇲🇼 Malawi (+265)", value: "MW" },
              { title: "🇲🇾 Malaysia (+60)", value: "MY" },
              { title: "🇲🇻 Maldives (+960)", value: "MV" },
              { title: "🇲🇱 Mali (+223)", value: "ML" },
              { title: "🇲🇹 Malta (+356)", value: "MT" },
              { title: "🇲🇷 Mauritania (+222)", value: "MR" },
              { title: "🇲🇺 Mauritius (+230)", value: "MU" },
              { title: "🇲🇽 Mexico (+52)", value: "MX" },
              { title: "🇲🇩 Moldova (+373)", value: "MD" },
              { title: "🇲🇨 Monaco (+377)", value: "MC" },
              { title: "🇲🇳 Mongolia (+976)", value: "MN" },
              { title: "🇲🇪 Montenegro (+382)", value: "ME" },
              { title: "🇲🇦 Morocco (+212)", value: "MA" },
              { title: "🇲🇿 Mozambique (+258)", value: "MZ" },
              { title: "🇲🇲 Myanmar (+95)", value: "MM" },
              { title: "🇳🇦 Namibia (+264)", value: "NA" },
              { title: "🇳🇵 Nepal (+977)", value: "NP" },
              { title: "🇳🇱 Netherlands (+31)", value: "NL" },
              { title: "🇳🇿 New Zealand (+64)", value: "NZ" },
              { title: "🇳🇮 Nicaragua (+505)", value: "NI" },
              { title: "🇳🇪 Niger (+227)", value: "NE" },
              { title: "🇳🇬 Nigeria (+234)", value: "NG" },
              { title: "🇰🇵 North Korea (+850)", value: "KP" },
              { title: "🇲🇰 North Macedonia (+389)", value: "MK" },
              { title: "🇳🇴 Norway (+47)", value: "NO" },
              { title: "🇴🇲 Oman (+968)", value: "OM" },
              { title: "🇵🇰 Pakistan (+92)", value: "PK" },
              { title: "🇵🇼 Palau (+680)", value: "PW" },
              { title: "🇵🇸 Palestine (+970)", value: "PS" },
              { title: "🇵🇦 Panama (+507)", value: "PA" },
              { title: "🇵🇬 Papua New Guinea (+675)", value: "PG" },
              { title: "🇵🇾 Paraguay (+595)", value: "PY" },
              { title: "🇵🇪 Peru (+51)", value: "PE" },
              { title: "🇵🇭 Philippines (+63)", value: "PH" },
              { title: "🇵🇱 Poland (+48)", value: "PL" },
              { title: "🇵🇹 Portugal (+351)", value: "PT" },
              { title: "🇶🇦 Qatar (+974)", value: "QA" },
              { title: "🇷🇴 Romania (+40)", value: "RO" },
              { title: "🇷🇺 Russia (+7)", value: "RU" },
              { title: "🇷🇼 Rwanda (+250)", value: "RW" },
              { title: "🇸🇦 Saudi Arabia (+966)", value: "SA" },
              { title: "🇸🇳 Senegal (+221)", value: "SN" },
              { title: "🇷🇸 Serbia (+381)", value: "RS" },
              { title: "🇸🇨 Seychelles (+248)", value: "SC" },
              { title: "🇸🇱 Sierra Leone (+232)", value: "SL" },
              { title: "🇸🇬 Singapore (+65)", value: "SG" },
              { title: "🇸🇰 Slovakia (+421)", value: "SK" },
              { title: "🇸🇮 Slovenia (+386)", value: "SI" },
              { title: "🇸🇴 Somalia (+252)", value: "SO" },
              { title: "🇿🇦 South Africa (+27)", value: "ZA" },
              { title: "🇰🇷 South Korea (+82)", value: "KR" },
              { title: "🇸🇸 South Sudan (+211)", value: "SS" },
              { title: "🇪🇸 Spain (+34)", value: "ES" },
              { title: "🇱🇰 Sri Lanka (+94)", value: "LK" },
              { title: "🇸🇩 Sudan (+249)", value: "SD" },
              { title: "🇸🇷 Suriname (+597)", value: "SR" },
              { title: "🇸🇪 Sweden (+46)", value: "SE" },
              { title: "🇨🇭 Switzerland (+41)", value: "CH" },
              { title: "🇸🇾 Syria (+963)", value: "SY" },
              { title: "🇹🇼 Taiwan (+886)", value: "TW" },
              { title: "🇹🇯 Tajikistan (+992)", value: "TJ" },
              { title: "🇹🇿 Tanzania (+255)", value: "TZ" },
              { title: "🇹🇭 Thailand (+66)", value: "TH" },
              { title: "🇹🇬 Togo (+228)", value: "TG" },
              { title: "🇹🇹 Trinidad and Tobago (+1-868)", value: "TT" },
              { title: "🇹🇳 Tunisia (+216)", value: "TN" },
              { title: "🇹🇷 Turkey (+90)", value: "TR" },
              { title: "🇹🇲 Turkmenistan (+993)", value: "TM" },
              { title: "🇺🇬 Uganda (+256)", value: "UG" },
              { title: "🇺🇦 Ukraine (+380)", value: "UA" },
              { title: "🇦🇪 United Arab Emirates (+971)", value: "AE" },
              { title: "🇬🇧 United Kingdom (+44)", value: "GB" },
              { title: "🇺🇸 United States (+1)", value: "US" },
              { title: "🇺🇾 Uruguay (+598)", value: "UY" },
              { title: "🇺🇿 Uzbekistan (+998)", value: "UZ" },
              { title: "🇻🇺 Vanuatu (+678)", value: "VU" },
              { title: "🇻🇦 Vatican City (+379)", value: "VA" },
              { title: "🇻🇪 Venezuela (+58)", value: "VE" },
              { title: "🇻🇳 Vietnam (+84)", value: "VN" },
              { title: "🇾🇪 Yemen (+967)", value: "YE" },
              { title: "🇿🇲 Zambia (+260)", value: "ZM" },
              { title: "🇿🇼 Zimbabwe (+263)", value: "ZW" },
            ],
          },
        },
      ],
      hidden: ({ parent }) => parent?.fieldType !== "tel",
    }),

  ],
  preview: {
    select: {
      label: "label",
      placeholder: "placeholder",
      required: "required",
    },
    prepare({ label, placeholder, required }) {
      return {
        title: label || placeholder || "Untitled",
        subtitle: required ? "Required" : "Optional",
      };
    },
  },
});
